modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
    modId="arsmagicalegacy"
    version="${file.jarVersion}"
    displayName="Ars Magica Legacy"
    authors="Minecraftschurli, IchHabeHunger54"
    description='''
    Legacy version of Ars Magica
    '''

[[dependencies.arsmagicalegacy]]
    modId="simpleorelib"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arsmagicalegacy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.arsmagicalegacy]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
