modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
    modId="arsmagicalegacy"
    version="${file.jarVersion}"
    displayName="Ars Magica Legacy"
    authors="Minecraftschurli"
    description='''
    Legacy version of Ars Magica
    '''
[[dependencies.arsmagicalegacy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.arsmagicalegacy]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
